version: '3'
services:
  soketi:
    image: 'quay.io/soketi/soketi:0.17-16-alpine'
    environment:
        DEBUG: '1'
        METRICS_SERVER_PORT: '9601'
    ports:
        - '${SOKETI_PORT:-6001}:6001'
        - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'